parameters:
- name: platforms
  type: object

jobs:
- ${{ each platform in parameters.platforms }}:
  - job: ''
    displayName: ${{ format('CrashReporter {0} Analyze and Test', platform) }}
    variables:
      XCODE_PATH: '/Applications/Xcode_14.3.1.app/Contents/Developer'
    templateContext:
      outputs:
      - output: pipelineArtifact
        displayName: 'Publish Diagnostic Reports'
        condition: failed()
        targetPath: /Users/runner/Library/Logs/DiagnosticReports
        artifactName: 'Test Diagnostic Reports'
        sbomEnabled: false

    steps:
    - checkout: self
      submodules: recursive
    - task: Xcode@5
      displayName: Analyze
      inputs:
        actions: analyze
        configuration: Debug
        xcodeVersion: specifyPath
        xcodeDeveloperDir: '$(XCODE_PATH)'
        xcWorkspacePath: CrashReporter.xcodeproj
        ${{ if eq(platform, 'MacCatalyst') }}:
          scheme: 'CrashReporter iOS'
          destinationPlatformOption: macOS
        ${{ if ne(platform, 'MacCatalyst') }}:
          scheme: 'CrashReporter ${{ platform }}'
          destinationPlatformOption: ${{ platform }}
        ${{ if eq(platform, 'iOS') }}:
          destinationSimulators: 'iPhone 11'
        ${{ if eq(platform, 'tvOS') }}:
          destinationSimulators: 'Apple TV'
          
    - task: Xcode@5
      displayName: Test
      inputs:
        actions: test
        configuration: Debug
        xcodeVersion: specifyPath
        xcodeDeveloperDir: '$(XCODE_PATH)'
        xcWorkspacePath: CrashReporter.xcodeproj
        ${{ if eq(platform, 'MacCatalyst') }}:
          scheme: 'CrashReporter iOS'
          destinationPlatformOption: macOS
        ${{ if ne(platform, 'MacCatalyst') }}:
          scheme: 'CrashReporter ${{ platform }}'
          destinationPlatformOption: ${{ platform }}
        ${{ if eq(platform, 'iOS') }}:
          destinationSimulators: 'iPhone 11'
        ${{ if eq(platform, 'tvOS') }}:
          destinationSimulators: 'Apple TV'
        publishJUnitResults: true
      timeoutInMinutes: 10